language: android

node_js:
  - 6.9.1

notifications:
  email: false

sudo: false

branches:
  only:
  - master

install:
  - cd ./anaf.app 
  # - echo y | android update sdk -u --filter android-22,android-23
  - npm install

script:
  - npm run build
  
release:
  - exit 0  